### ISSUE TITLE
5.0.3 Mediapipe 初始化卡在75%

### ISSUE THREAD

**Issue by dennishuang85** [endink/mediapipe-ue-export#1]
您好，我看到您在wongfei的mediapipe UE4的项目下回复关于5.0.3 初始化卡在75%的问题。我尝试了您的方案。
我在项目的build.cs下添加delay loading dll后，有这个报错
1>D:\VokaDemo2292\Source\fBlahMediaOutput\fBlahMediaOutput.Build.cs(15,29): error CS1501: No overload for method 'Add' takes 8 arguments
1>UnrealBuildTool : error : Expecting to find a type to be declared in a target rules named 'fBlahMediaOutputEditorTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
然后在mediapipe的Binaries\Win64 中将所有dll复制到了项目的Binaries\Win64下，但还是会卡75%。 

另外，在5.0.1中是正常初始化，但工程build后 control rig失效。所以才希望能升级到5.0.3.

请问该问题是否有解决方案。感谢。

**Comment by endink** [comment]
首先你需要延迟加载，不要在 editor 环境把 DLL 放到 Binaries 目录，这样你可以顺利的启动 EDITOR 环境。
打包环境下你还是需要修改字节，除非 epic 官方修复这个问题，我那个回复只是正对他所说的 editor 环境可能要重新编译引擎，其实不需要的，不要让 editor 去  load 就可以了

**Comment by endink** [comment]
你没有贴出代码，我不知道你的 build.cs 怎么写的，5.0.3 当然没有问题，我就是这个环境

**Comment by endink** [comment]
BTW， 你不需要手工拷贝任何 DLL，参考将以下函数放到的 build.cs 文件，然后传入你插件里的 DLL 路径：

```csharp
private void AddDLLDependency(string sourceFile)
	{
		string fileName = Path.GetFileName(sourceFile);
		PublicDelayLoadDLLs.Add(fileName);
		string dst = "$(TargetOutputDir)/" + fileName;
		RuntimeDependencies.Add(dst, sourceFile);
	}
```
调用：

```csharp
string apiDll = Path.Combine(ModuleDirectory, "DLL", "Win64", "mediapipe_api.dll");
AddDLLDependency(apiDll);
```

这样会在你打包时候自动帮你拷贝到输出目录，但是 editor 时候不会做任何拷贝，你的代码需要宏定义处理 dll 的 editor 路径和打包路径，这个可以解决 editor 75% 问题，但是注意，打包时候一定要修改字节，否则你打包出来的程序依旧要卡住。

**Comment by dennishuang85** [comment]
好的，我试试。感谢

**Comment by dennishuang85** [comment]
> 

您所说的打包时候需要修改字节，请问修改的字节部分可以也说一下吗？

**Comment by endink** [comment]
他的代码里有了，  fix dead lock那段代码

**Comment by dennishuang85** [comment]
> 

您指的是wongfei的代码？ 我没找到有这一段

**Comment by endink** [comment]
是的，我这个代码是 mediapipe 代码，和 UE 没关系

**Comment by dennishuang85** [comment]
> 

这个可以详细说一下吗。我对mediapipe的代码不熟。感谢

**Comment by dennishuang85** [comment]
string apiDll = Path.Combine(ModuleDirectory, "DLL", "Win64", "mediapipe_api.dll");
AddDLLDependency(apiDll);
这个调用我应该在哪里调用呢

**Comment by endink** [comment]
额， 这是 C# 代码，是放在你的插件项目的 build.cs 里的 ，不是给你调用的，你需要加载 mediapipe 编译出来的 dll 啊，wongfei 编译的 dll 是 ump.dll ，我的是mediapipe_api.dll，这些名字和路径你要根据自己的情况改一下吧

**Comment by 13122352840** [comment]
>[1/4] Compile MediaPipeModule.cpp
1>[2/4] Link UnrealEditor-MediaPipe.lib
1>  正在创建库 D:\VokaDemo2292\Plugins\MediaPipe\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe\UnrealEditor-MediaPipe.lib 和对象 D:\VokaDemo2292\Plugins\MediaPipe\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe\UnrealEditor-MediaPipe.exp
1>[3/4] Link UnrealEditor-MediaPipe.dll
1>  正在创建库 D:\VokaDemo2292\Plugins\MediaPipe\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe\UnrealEditor-MediaPipe.suppressed.lib 和对象 D:\VokaDemo2292\Plugins\MediaPipe\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe\UnrealEditor-MediaPipe.suppressed.exp
1>[4/4] WriteMetadata fBlahMediaOutputEditor.target
1>Total time in Parallel executor: 5.51 seconds
所以我这个应该是 UnrealEditor-MediaPipe.dll吧？

**Comment by 13122352840** [comment]
我按照您前面说的加了，但是编译会有这个报错Expecting to find a type to be declared in a target rules named 'fBlahMediaOutputEditorTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
能告诉我要怎么改吗，感谢。我的dll路径是 ..\..\Plugins\MediaPipe\Binaries\Win64\UnrealEditor-MediaPipe.dll
build.cs代码如下
using UnrealBuildTool;
using System.IO;

public class MediaPipe : ModuleRules
{
    public MediaPipe(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.NoPCHs; // UseExplicitOrSharedPCHs;
        bUseUnity = false;
        bUseRTTI = true;

        PublicDependencyModuleNames.AddRange(
            new string[] {
                "Core",
                "CoreUObject",
                "Engine",
                "InputCore",
                "Slate",
                "SlateCore",
                "RHI",
                "RenderCore"
            }
        );

        PrivateDependencyModuleNames.AddRange(
            new string[] {
                "Projects",
            }
        );

        string BinArch = Target.Platform.ToString();
        string LibExt = "";
        string DllExt = ".so";

        if (Target.Platform == UnrealTargetPlatform.Win64)
        {
            LibExt = ".lib";
            DllExt = ".dll";
        }

        string BinaryOutputDir = "$(BinaryOutputDir)";
        string ThirdPartyDir = Path.Combine(ModuleDirectory, "..", "..", "ThirdParty");



        // onnxruntime deps

        string OnnxruntimeBinDir = Path.Combine(ThirdPartyDir, "onnxruntime", "Binaries", BinArch);
        AddDep("onnxruntime", DllExt, OnnxruntimeBinDir, BinaryOutputDir);

        // protobuf deps

        if (Target.Platform == UnrealTargetPlatform.Win64)
        {
            PublicDefinitions.Add("PROTOBUF_USE_DLLS=1");
        }

        PublicIncludePaths.Add(Path.Combine(ThirdPartyDir, "protobuf", "Include"));
        PublicAdditionalLibraries.Add(Path.Combine(ThirdPartyDir, "protobuf", "Lib", BinArch, "libprotobuf" + LibExt));

        string ProtobufBinDir = Path.Combine(ThirdPartyDir, "protobuf", "Binaries", BinArch);
        AddDep("libprotobuf", DllExt, ProtobufBinDir, BinaryOutputDir);

        // mediapipe deps

        string MPBinDir = Path.Combine(ThirdPartyDir, "mediapipe", "Binaries", BinArch);
        string MPDataDir = Path.Combine(ThirdPartyDir, "mediapipe", "Data");
        string MPModelDir = Path.Combine(ThirdPartyDir, "mediapipe", "models");

        AddDep("opencv_world3410", DllExt, MPBinDir, BinaryOutputDir);
        AddDep("opencv_world410", DllExt, MPBinDir, BinaryOutputDir);
        AddDep("ump_shared", DllExt, MPBinDir, BinaryOutputDir);
        //AddDep("DLLEigenMain", DllExt, MPBinDir, BinaryOutputDir);
        AddDep("TongueDetection", DllExt, MPBinDir, BinaryOutputDir);

        if (Target.Type != TargetType.Editor)
        {
            AddDepFolder(MPDataDir, BinaryOutputDir);
            AddDepFolder(MPModelDir, BinaryOutputDir);
        }
    }

    private void AddDep(string FileName, string Ext, string SourceDir, string TargetDir)
    {
        RuntimeDependencies.Add(Path.Combine(TargetDir, FileName + Ext), Path.Combine(SourceDir, FileName + Ext));
    }

    private void AddDepFolder(string SourceDir, string TargetDir)
    {
        foreach (string filePath in Directory.GetFiles(SourceDir, "*.*", SearchOption.AllDirectories))
        {
            string dst = filePath.Replace(SourceDir, TargetDir);
            RuntimeDependencies.Add(dst, filePath);
        }
    }

    private void AddDLLDependency(string sourceFile)
    {
        string fileName = Path.GetFileName(sourceFile);
        PublicDelayLoadDLLs.Add(fileName);
        string dst = "$(TargetOutputDir)/" + fileName;
        RuntimeDependencies.Add(dst, sourceFile);
    }
    
    string apiDll = Path.Combine(ModuleDirectory, "Binaries", "Win64", "UnrealEditor-MediaPipe.dll");
    AddDLLDependency(apiDll);


}

**Comment by endink** [comment]
@13122352840 

AddDLLDependency(apiDll); 这里的 dll 是指你 mediapipe 的 DLL，你的代码里是 
- ump_shared.dll
- libprotobuf.dll
- opencv_world3410.dll
---
路径要完整路径，你的 AddDep 和我这个函数是一样的，你可以删除 AddDep，替换成 AddDLLDependency

**Comment by 13122352840** [comment]
是这样改吗？
         //AddDep("opencv_world3410", DllExt, MPBinDir, BinaryOutputDir);
         //AddDep("opencv_world410", DllExt, MPBinDir, BinaryOutputDir);
        //AddDep("ump_shared", DllExt, MPBinDir, BinaryOutputDir);
       ////AddDep("DLLEigenMain", DllExt, MPBinDir, BinaryOutputDir);
        //AddDep("TongueDetection", DllExt, MPBinDir, BinaryOutputDir);
        //private void AddDep(string FileName, string Ext, string SourceDir, string TargetDir)
    //{
    //    RuntimeDependencies.Add(Path.Combine(TargetDir, FileName + Ext), Path.Combine(SourceDir, FileName + Ext));
    //}
AddDLLDependency("E:\VokaDemo\Plugins\MediaPipe\Binaries\Win64\libprotobuf.dll");
AddDLLDependency("E:\VokaDemo\Plugins\MediaPipe\Binaries\Win64\opencv_world3410.dll");
AddDLLDependency("E:\VokaDemo\Plugins\MediaPipe\Binaries\Win64\libprotobuf.dll");

**Comment by endink** [comment]
是的，你代码里要区分编辑器时候的路径和打包路径来 load 这些 dll

**Comment by 13122352840** [comment]
您有微信吗？或者别的联系方式？

**Comment by 13122352840** [comment]
请问这个编译报错怎么解决呢
1>------ 已启动生成: 项目: fBlahMediaOutput, 配置: Development_Editor x64 ------
1>Using bundled DotNet SDK
1>Log file: C:\Users\VOKA\AppData\Local\UnrealBuildTool\Log.txt
1>Invalidating makefile for fBlahMediaOutputEditor (MediaPipe.Build.cs modified)
1>UnrealBuildTool : warning : Errors generated while parsing 'D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs'
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,25): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,34): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,42): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,52): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,61): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,67): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,25): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,34): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,42): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,52): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,61): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,67): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,25): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,34): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,42): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,52): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,61): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,67): error CS1009: Unrecognized escape sequence
1>UnrealBuildTool : error : Expecting to find a type to be declared in a target rules named 'fBlahMediaOutputEditorTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: 命令“"D:\Program Files\Epic Games\UE_5.0\Engine\Build\BatchFiles\Build.bat" fBlahMediaOutputEditor Win64 Development -Project="D:\VokaDemo2292\fBlahMediaOutput.uproject" -WaitMutex -FromMsBuild”已退出，代码为 6。
1>已完成生成项目“fBlahMediaOutput.vcxproj”的操作 - 失败。
========== “生成”: 0 成功，1 失败，0 更新，0 已跳过 ==========
