### ISSUE TITLE
5.0.3 Mediapipe 初始化卡在75% 

### ISSUE THREAD

**Issue by 13122352840** [endink/mediapipe-ue-export#2]
请问这个编译报错怎么解决呢
1>------ 已启动生成: 项目: fBlahMediaOutput, 配置: Development_Editor x64 ------
1>Using bundled DotNet SDK
1>Log file: C:\Users\VOKA\AppData\Local\UnrealBuildTool\Log.txt
1>Invalidating makefile for fBlahMediaOutputEditor (MediaPipe.Build.cs modified)
1>UnrealBuildTool : warning : Errors generated while parsing 'D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs'
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,25): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,34): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,42): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,52): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,61): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(107,67): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,25): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,34): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,42): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,52): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,61): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(108,67): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,25): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,34): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,42): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,52): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,61): error CS1009: Unrecognized escape sequence
1>D:\VokaDemo2292\Plugins\MediaPipe\Source\MediaPipe\MediaPipe.Build.cs(109,67): error CS1009: Unrecognized escape sequence
1>UnrealBuildTool : error : Expecting to find a type to be declared in a target rules named 'fBlahMediaOutputEditorTarget'. This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: 命令“"D:\Program Files\Epic Games\UE_5.0\Engine\Build\BatchFiles\Build.bat" fBlahMediaOutputEditor Win64 Development -Project="D:\VokaDemo2292\fBlahMediaOutput.uproject" -WaitMutex -FromMsBuild”已退出，代码为 6。
1>已完成生成项目“fBlahMediaOutput.vcxproj”的操作 - 失败。
========== “生成”: 0 成功，1 失败，0 更新，0 已跳过 ==========

**Comment by endink** [comment]
参考解决方案：

https://forums.unrealengine.com/t/fplatformprocess-getdllhandle-causes-deadlock-when-loading-opencv-world/571735/9
